import React from 'react';
import Header from '../layout/Header';
import Navbar from '../layout/Navbar';
import './privacy.css'

function Privacy(){
    return(
        <>
        <Header />
        <Navbar />
        <div className='mt-10 md:mt-20 w-full p-5 md:w-2/3  m-auto title_font'>
            <p className='text-[38px] text-[#0F1A2F] font-semibold'>Privacy Policy</p>
            <p className='text-[20px] text-gray-500  mt-5'>Effective date: <label className='text-[#0F1A2F] font-bold'>Sep 12, 2022 </label></p>

            <p className='text-[20px] text-gray-500  mt-5'>Highware Solutions ("us", "we", or "our") operates the <label className='text-[#9B7BF7] underline'>linkdrip.io</label> website (hereinafter referred to as the "Service").</p>
            <p className='text-[20px] text-gray-500  mt-5'>This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>
            <p className='text-[20px] text-gray-500  mt-5'>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from <label className='text-[#9B7BF7] underline'>linkdrip.io</label></p>
            
            <p className='text-[38px] text-[#0F1A2F] font-semibold mt-10'>Definitions</p>
            
            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>Service</p>
            <p className='text-[20px] text-gray-500'>‍Service is the <label className='text-[#9B7BF7] underline'>linkdrip.io</label> website operated by Highware Solutions</p>

            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>Personal Data</p>
            <p className='text-[20px] text-gray-500'>‍‍Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>

            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>‍Usage Data</p>
            <p className='text-[20px] text-gray-500'>‍‍‍Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
       
            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>‍Cookies</p>
            <p className='text-[20px] text-gray-500'>Cookies are small files stored on your device (computer or mobile device).</p>
       
            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>Data Controller</p>
            <p className='text-[20px] text-gray-500'>‍‍‍‍Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>
       
            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>‍Data Processors (or Service Providers)</p>
            <p className='text-[20px] text-gray-500'>‍‍‍‍‍Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.We may use the services of various Service Providers in order to process your data more effectively.</p>
       
            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>‍Data Subject (or User)</p>
            <p className='text-[20px] text-gray-500'>‍‍‍‍‍Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p>
       
            <p className='text-[38px] text-[#0F1A2F] font-semibold mt-10'>Information Collection and Use</p>

            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍We collect several different types of information for various purposes to provide and improve our Service to you.</p>

            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>‍Personal Data</p>
            <p className='text-[20px] text-gray-500'>‍‍‍‍‍While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>

            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>Email address</p>
            
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍Cookies and Usage Data</p>
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send or by contacting us.</p>

            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>Usage Data</p>
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>Tracking & Cookies Data</p>
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍‍We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
      
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍Examples of Cookies we use:</p>
      
            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>‍Session Cookies.</p>
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍We use Session Cookies to operate our Service.</p>

            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>‍Preference Cookies.</p>
            <p className='text-[20px] text-gray-500 mt-5'>We use Preference Cookies to remember your preferences and various settings.</p>

            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>‍Security Cookies.</p>    
            <p className='text-[20px] text-gray-500 mt-5'>We use Security Cookies for security purposes.</p>
      
      
            <p className='text-[38px] text-[#0F1A2F] font-semibold mt-10'>Use of Data</p>

            <p className='text-[20px] text-gray-500 mt-5'>LinkDrip uses the collected data for various purposes:</p>
            <p className='text-[20px] text-gray-500 '>- To provide and maintain our Service</p>
            <p className='text-[20px] text-gray-500 '>- To notify you about changes to our Service</p>
            <p className='text-[20px] text-gray-500 '>- To allow you to participate in interactive features of our Service when you choose to do so</p>
            <p className='text-[20px] text-gray-500 '>- To provide customer support</p>
            <p className='text-[20px] text-gray-500 '>- To gather analysis or valuable information so that we can improve our Service</p>
            <p className='text-[20px] text-gray-500 '>- To detect, prevent and address technical issues</p>
            <p className='text-[20px] text-gray-500 '>- To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</p>

            <p className='text-[38px] text-[#0F1A2F] font-semibold mt-10'>Legal Basis for Processing Personal Data under the General Data Protection Regulation (GDPR)</p>
            <p className='text-[20px] text-gray-500 mt-5 '>If you are from the European Economic Area (EEA), LinkDrip legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</p>
            <p className='text-[20px] text-gray-500 mt-5 '>LinkDrip may process your Personal Data because:</p>
            <p className='text-[20px] text-gray-500  '> We need to perform a contract with you</p>
            <p className='text-[20px] text-gray-500  '>- You have given us permission to do so</p>
            <p className='text-[20px] text-gray-500  '>- The processing is in our legitimate interests and it is not overridden by your rights</p>
            <p className='text-[20px] text-gray-500  '>- For payment processing purposesTo comply with the law</p>

            <p className='text-[38px] text-[#0F1A2F] font-semibold mt-10'>Retention of Data</p>
            <p className='text-[20px] text-gray-500 mt-5'>LinkDrip will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies.</p>
            <p className='text-[20px] text-gray-500 mt-5'>LinkDrip will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.</p>

            <p className='text-[38px] text-[#0F1A2F] font-semibold mt-10'>Transfer of Data</p>
            <p className='text-[20px] text-gray-500 mt-5'>Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
            <p className='text-[20px] text-gray-500 mt-5'>If you are located outside Europe and choose to provide information to us, please note that we transfer the data, including Personal Data, to Switzerland, and process it there.</p>  
            <p className='text-[20px] text-gray-500 mt-5'>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
            <p className='text-[20px] text-gray-500 mt-5'>LinkDrip will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
      
            <p className='text-[38px] text-[#0F1A2F] font-semibold mt-10'>Disclosure of Data</p>

            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>‍Business Transaction</p>
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍If LinkDrip is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
      
            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>Disclosure for Law Enforcement</p>
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍‍Under certain circumstances, LinkDrip may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
      
            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>Legal Requirements</p>
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍‍‍LinkDrip may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
            <p className='text-[20px] text-gray-500'>‍‍‍‍‍‍‍‍- To comply with a legal obligation</p>
            <p className='text-[20px] text-gray-500'>‍‍‍‍‍‍‍‍- To protect and defend the rights or property of LinkDrip</p>
            <p className='text-[20px] text-gray-500'>‍‍‍‍‍‍‍‍- To prevent or investigate possible wrongdoing in connection with the Service</p>
            <p className='text-[20px] text-gray-500'>‍‍‍‍‍‍‍‍- To protect the personal safety of users of the Service or the public</p>
            <p className='text-[20px] text-gray-500'>‍‍‍‍‍‍‍‍- To protect against legal liability</p>

            <p className='text-[38px] text-[#0F1A2F] font-semibold mt-10'>Security of Data</p>
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍‍‍The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

            <p className='text-[38px] text-[#0F1A2F] font-semibold mt-10'>Our Policy on "Do Not Track" Signals under the California Online Protection Act (CalOPPA)</p>
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍‍‍We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.</p>
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍‍‍You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>
            

            <p className='text-[38px] text-[#0F1A2F] font-semibold mt-10'>Your Data Protection Rights under the General Data Protection Regulation (GDPR)</p>
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍‍‍If you are a resident of the European Economic Area (EEA), you have certain data protection rights. LinkDrip aims to take reasonable steps to allow you to correct, amend, delete or limit the use of your Personal Data.</p>
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍‍‍If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.</p>

            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍‍‍In certain circumstances, you have the following data protection rights:</p>  
            <p className='text-[20px] text-gray-500 '>‍‍‍‍‍‍‍‍<label className='text-[#0F1A2F] font-bold'>The right to access, update or delete the information we have on you.</label> Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</p>  
            <p className='text-[20px] text-gray-500 '>‍‍‍‍‍‍‍‍‍<label className='text-[#0F1A2F] font-bold'>The right of rectification.</label> You have the right to have your information rectified if that information is inaccurate or incomplete.</p>  
            <p className='text-[20px] text-gray-500 '>‍‍‍‍‍‍‍‍‍<label className='text-[#0F1A2F] font-bold'>The right to object.</label> You have the right to object to our processing of your Personal Data.</p>  
            <p className='text-[20px] text-gray-500 '>‍‍‍‍‍‍‍‍‍<label className='text-[#0F1A2F] font-bold'>The right of restriction.</label> You have the right to request that we restrict the processing of your personal information.</p>  
            <p className='text-[20px] text-gray-500 '>‍‍‍‍‍‍‍‍‍<label className='text-[#0F1A2F] font-bold'>The right to data portability.</label> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</p>  
            <p className='text-[20px] text-gray-500 '>‍‍‍‍‍‍‍‍‍<label className='text-[#0F1A2F] font-bold'>The right to withdraw consent. </label>You also have the right to withdraw your consent at any time where LinkDrip relied on your consent to process your personal information.</p>  
            <p className='text-[20px] text-gray-500 '>‍‍‍‍‍‍‍‍Please note that we may ask you to verify your identity before responding to such requests.</p>  
            <p className='text-[20px] text-gray-500 '>‍‍‍‍‍‍‍‍You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>  

            <p className='text-[38px] text-[#0F1A2F] font-semibold mt-10'>Service Providers</p>
            <p className='text-[20px] text-gray-500 '>‍‍‍‍‍‍‍‍We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>  
            <p className='text-[20px] text-gray-500 '>‍‍‍‍‍‍‍‍These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>  
      
            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>Analytics</p>    
            <p className='text-[20px] text-gray-500 mt-5'>We may use third-party Service Providers to monitor and analyse the use of our Service.</p>

            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>Payments</p>    
            <p className='text-[20px] text-gray-500 mt-5'>‍We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).</p>
      
            <p className='text-[20px] text-gray-500 mt-5'>‍We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, MasterCard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>

            <p className='text-[20px] text-gray-500 mt-5'>‍The payment processors we work with are:</p>

            <p className='text-[#0F1A2F] font-bold text-[20px] mt-5 '>Stripe</p>    
            <p className='text-[20px] text-gray-500 mt-5'>‍‍Their Privacy Policy can be viewed at <label className='text-[#9B7BF7] underline'> https://stripe.com/us/privacy</label></p>

            <p className='text-[38px] text-[#0F1A2F] font-semibold mt-10'>Links to Other Sites</p>
            <p className='text-[20px] text-gray-500 '>‍‍‍‍‍‍‍‍Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>  
            <p className='text-[20px] text-gray-500 '>‍‍‍‍‍‍‍‍We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>  

            <p className='text-[38px] text-[#0F1A2F] font-semibold mt-10'>Children's Privacy</p>
            <p className='text-[20px] text-gray-500 '>‍‍‍‍‍‍‍‍Our Service does not address anyone under the age of 18 ("Children").</p>  
            <p className='text-[20px] text-gray-500 '>‍‍‍‍‍‍‍‍We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>    
      
            <p className='text-[38px] text-[#0F1A2F] font-semibold mt-10'>Changes to This Privacy Policy</p>
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍‍‍We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>  
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍‍‍We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>  
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍‍‍You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>  
            
            <p className='text-[38px] text-[#0F1A2F] font-semibold mt-10'>Contact Us</p>
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍‍‍If you have any questions about these terms, please contact us:</p>  
            <p className='text-[20px] text-gray-500 mt-5'>‍‍‍‍‍‍‍‍By email:<label className='text-[#9B7BF7] underline'> support@linkdrip.io</label></p>  

      </div>
       </>
    )
}

export default Privacy;